duckdb_file: actup.duckdb
exclude_repo_paths: [.github]

exclude_repos:
  - atom/atom
  - ryanoasis/nerd-fonts
  - TapXWorld/ChinaTextbook
  - traefik/traefik

github_api_base_url: https://api.github.com
pat_github_env_var: PAT_GITHUB
popular_actions_limit: 8000
popular_repos_limit: 250
temp_dir: temp_scan
