duckdb_file: actup.duckdb
exclude_repo_paths: [.github]
github_api_base_url: https://api.github.com
pat_github_env_var: PAT_GITHUB
popular_actions_limit: 1000
popular_repos_limit: 25
temp_dir: temp_scan